package com.kafka.demo.kafka_demo.entity;
import java.util.Date;

public class TrainingInfo {
    private Integer id;

    private Integer trainContent;

    private Integer algoId;

    private Integer status;

    private Date beginTime;

    private Date endTime;

    private Date createTime;

    private Date deleteTime;

    private Integer createPerson;
    private Integer isAvailable;

    //当前页码
    private int currentPage;

    //起始数据偏移量
    private int offset;

    //页面数据条数
    private int pageSize;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTrainContent() {
        return trainContent;
    }

    public void setTrainContent(Integer trainContent) {
        this.trainContent = trainContent;
    }

    public Integer getAlgoId() {
        return algoId;
    }

    public void setAlgoId(Integer algoId) {
        this.algoId = algoId;
    }

    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.status
     *
     * @param status the value for public.algo_training_info.status
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.begin_time
     *
     * @return the value of public.algo_training_info.begin_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.begin_time
     *
     * @param beginTime the value for public.algo_training_info.begin_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.end_time
     *
     * @return the value of public.algo_training_info.end_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.end_time
     *
     * @param endTime the value for public.algo_training_info.end_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.create_time
     *
     * @return the value of public.algo_training_info.create_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.create_time
     *
     * @param createTime the value for public.algo_training_info.create_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.delete_time
     *
     * @return the value of public.algo_training_info.delete_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.delete_time
     *
     * @param deleteTime the value for public.algo_training_info.delete_time
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.create_person
     *
     * @return the value of public.algo_training_info.create_person
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.create_person
     *
     * @param createPerson the value for public.algo_training_info.create_person
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.algo_training_info.is_available
     *
     * @return the value of public.algo_training_info.is_available
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public Integer getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.algo_training_info.is_available
     *
     * @param isAvailable the value for public.algo_training_info.is_available
     *
     * @mbggenerated Thu Feb 27 15:38:27 CST 2020
     */
    public void setIsAvailable(Integer isAvailable) {
        this.isAvailable = isAvailable;
    }

    public int getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(int currentPage) {
        this.currentPage = currentPage;
    }

    public int getOffset() {
        return (currentPage-1)*pageSize;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }
}